import java.util.HashSet;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * RSS Aggregator program reads multiple RSS feeds and generates nicely
 * formatted HTML page of links for each feed, plus an HTML index page with
 * links to the individual feed pages. The ads/sponsors links and duplicate
 * entries contained in the feeds are filtered out. .
 *
 * @author Chris Ma
 */
public final class RSSAggregator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregator() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method: <pre>
     *
     * <!DOCTYPE html>
     * <html lang="en">
     * <head>
     *  <title>the channel tag title as the page title</title>
     * </head>
     * <body>
     *  <h1>the page title inside a link to the <channel> link</h1>
     *  <p>
     *  the channel description
     *  </p>
     *  <table border="1">
     *   <tbody>
     *    <tr>
     *     <th>Date</th>
     *     <th>Source</th>
     *     <th>News</th>
     *    </tr>
     *
     * </pre> Note: pre open & close tags are just for formatting this comment.
     * Method output should not include pre tags.
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        int titleIndex = getChildElement(channel, "title");
        String title = "No Title";
        if (titleIndex != -1 && channel.child(titleIndex).numberOfChildren() > 0) {
            title = channel.child(titleIndex).child(0).label();
        }

        int linkIndex = getChildElement(channel, "link");
        String link = "";
        if (linkIndex != -1 && channel.child(linkIndex).numberOfChildren() > 0) {
            link = channel.child(linkIndex).child(0).label();
        }

        int descIndex = getChildElement(channel, "description");
        String description = "";
        if (descIndex != -1 && channel.child(descIndex).numberOfChildren() > 0) {
            description = channel.child(descIndex).child(0).label();
        }

        out.println("<!DOCTYPE html>");
        out.println("<html lang=\"en\">");
        out.println("<head>");
        out.println("<meta charset=\"UTF-8\">");
        out.println("<title>" + title + "</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1><a href=\"" + link + "\">" + title + "</a></h1>");
        out.println("<p>" + description + "</p>");
        out.println("<table border=\"1\">");
        out.println("<tbody>");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method: <pre>
     *
     * </tbody>
     * </table>
     * </body>
     * </html>
     *
     * </pre> Note: pre open & close tags are just for formatting this comment.
     * Method output should not include pre tags.
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        out.println("</tbody>");
        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first tag child of the {@code XMLTree} matching the
     *  given tag or -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        for (int i = 0; i < xml.numberOfChildren(); i++) {
            if (xml.child(i).isTag() && xml.child(i).label().equals(tag)) {
                return i;
            }
        }
        return -1;
    }

    /**
     * Determines whether an item link is likely to be an advertisement or
     * sponsor.
     *
     * @param feed
     *            the feed content to check
     * @return true if it's probably an ad/sponsor link, false otherwise
     */
    private static boolean isAdLink(String feed) {
        if (feed == null) {
            return false;
        }

        final Pattern adsUrlPattern = Pattern
                .compile(
                        ".*//(?:ad|ads|adserver|adnetwork|advertising|"
                                + "googlesyndication|tracker)\\..*|"
                                + ".*\\?utm_source=.*\\&utm_medium=.*",
                        Pattern.CASE_INSENSITIVE);

        Matcher feedMatcher = adsUrlPattern.matcher(feed);
        return (feedMatcher.find());

        // The following brute-force match was considered but abandoned
        // due to many false positives.

        // String lower = feed.toLowerCase();
        // return lower.contains("ad.") || lower.contains("ads.")
        //        || lower.contains("advertisement") || lower.contains("sponsor")
        //        || lower.contains("doubleclick") || lower.contains("tracking")
        //        || lower.contains("promo");
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item")
                : "" + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        out.print("<tr>");

        // Date
        int dateIndex = getChildElement(item, "pubDate");
        String date = (dateIndex != -1 && item.child(dateIndex).numberOfChildren() > 0)
                ? item.child(dateIndex).child(0).label()
                : "No date available";
        out.print("<td>" + date + "</td>");

        // Source
        int sourceIndex = getChildElement(item, "source");
        if (sourceIndex != -1 && item.child(sourceIndex).numberOfChildren() > 0) {
            String sourceText = item.child(sourceIndex).child(0).label();
            String sourceUrl = item.child(sourceIndex).attributeValue("url");
            out.print("<td><a href=\"" + sourceUrl + "\">" + sourceText + "</a></td>");
        } else {
            out.print("<td>No source available</td>");
        }

        // Title / Description
        int titleIndex = getChildElement(item, "title");
        int descIndex = getChildElement(item, "description");
        String title = "No title available";
        if (titleIndex != -1 && item.child(titleIndex).numberOfChildren() > 0) {
            title = item.child(titleIndex).child(0).label();
        } else if (descIndex != -1 && item.child(descIndex).numberOfChildren() > 0) {
            title = item.child(descIndex).child(0).label();
        }

        int linkIndex = getChildElement(item, "link");
        String link = "";
        if (linkIndex != -1 && item.child(linkIndex).numberOfChildren() > 0) {
            link = item.child(linkIndex).child(0).label();
        }

        if (!link.equals("")) {
            out.print("<td><a href=\"" + link + "\">" + title + "</a></td>");
        } else {
            out.print("<td>" + title + "</td>");
        }

        out.println("</tr>");

    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        try {
            XMLTree rss = new XMLTree1(url);
            if (!rss.label().equals("rss")
                    || !rss.attributeValue("version").equals("2.0")) {
                out.println("Skipping invalid RSS feed: " + url);
                return;
            }

            XMLTree channel = rss.child(getChildElement(rss, "channel"));
            SimpleWriter fileOut = new SimpleWriter1L(file);
            outputHeader(channel, fileOut);

            // Track seen links/titles
            // HashSet does not allow duplicate elements.
            Set<String> seen = new HashSet<>();

            for (int i = 0; i < channel.numberOfChildren(); i++) {
                XMLTree child = channel.child(i);
                if (child.isTag() && child.label().equals("item")) {
                    // Skip the item if it contains advertisement or sponsor links.
                    if (!isAdLink(child.toString())) {
                        // If the item can be added to HashSet, it is not duplicate.
                        if (seen.add(child.toString().strip())) {
                            processItem(child, fileOut);
                        } else {
                            out.println("Skipped duplicate item: " + child.toString());
                        }
                    } else {
                        out.println("Skipped ads/sponsor item: " + child.toString());
                    }
                }
            }

            outputFooter(fileOut);
            fileOut.close();

            out.println("Processed feed: " + url + " → " + file);

        } catch (Exception e) {
            out.println("Error processing feed: " + url);
        }
    }

    /**
     * Main: Reads feeds list, processes each, builds index page.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        out.print("Enter XML file with list of feeds: ");
        String feedsFile = in.nextLine();
        XMLTree feedsXML = new XMLTree1(feedsFile);

        while (!feedsXML.hasAttribute("title") || feedsXML.numberOfChildren() == 0) {
            out.println("Error: Invalid xml input File");
            out.print("Enter XML file with list of feeds: ");
            feedsFile = in.nextLine();
            feedsXML = new XMLTree1(feedsFile);
        }

        out.print("Enter name for the output index HTML file: ");
        String indexFileName = in.nextLine();
        SimpleWriter indexOut = new SimpleWriter1L(indexFileName);

        String pageTitle = feedsXML.attributeValue("title");

        // Start index page
        indexOut.println("<!DOCTYPE html>");
        indexOut.println("<html lang=\"en\">");
        indexOut.println("<head>");
        indexOut.println("<meta charset=\"UTF-8\">");
        indexOut.println("<title>" + pageTitle + "</title>");
        indexOut.println("</head>");
        indexOut.println("<body>");
        indexOut.println("<h2>" + pageTitle + "</h2>");
        indexOut.println("<ul>");

        for (int i = 0; i < feedsXML.numberOfChildren(); i++) {
            XMLTree feed = feedsXML.child(i);
            if (feed.label().equals("feed")) {
                String url = feed.attributeValue("url");
                String name = feed.attributeValue("name");
                String file = feed.attributeValue("file");

                processFeed(url, file, out);
                indexOut.println("<li><a href=\"" + file + "\">" + name + "</a></li>");
            }
        }

        // Finish index page
        indexOut.println("</ul>");
        indexOut.println("</body>");
        indexOut.println("</html>");

        out.println("Completed!");

        in.close();
        out.close();
        indexOut.close();
    }
}
