import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Put your name here
 *
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method: <pre>
     *
     * <!DOCTYPE html>
     * <html lang="en">
     * <head>
     *  <title>the channel tag title as the page title</title>
     * </head>
     * <body>
     *  <h1>the page title inside a link to the <channel> link</h1>
     *  <p>
     *  the channel description
     *  </p>
     *  <table border="1">
     *   <tr>
     *    <th>Date</th>
     *    <th>Source</th>
     *    <th>News</th>
     *   </tr>
     *
     * </pre> Note: pre open & close tags are just for formatting this comment.
     * Method output should not include pre tags.
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel")
                : "" + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        int titleIndex = getChildElement(channel, "title");
        String title = "Empty Title";
        if (titleIndex != -1 && channel.child(titleIndex).numberOfChildren() > 0) {
            title = channel.child(titleIndex).child(0).label();
        }

        int linkIndex = getChildElement(channel, "link");
        String link = "";
        if (linkIndex != -1 && channel.child(linkIndex).numberOfChildren() > 0) {
            link = channel.child(linkIndex).child(0).label();
        }

        int descIndex = getChildElement(channel, "description");
        String description = "";
        if (descIndex != -1 && channel.child(descIndex).numberOfChildren() > 0) {
            description = channel.child(descIndex).child(0).label();
        }

        out.println("<!DOCTYPE html>");
        out.println("<html lang=\"en\">");
        out.println("<head>");
        out.println("<title>" + title + "</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1><a href=\"" + link + "\">" + title + "</a></h1>");
        out.println("<p>" + description + "</p>");
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method: <pre>
     *
     *  </table>
     * </body>
     * </html>
     *
     * </pre> Note: pre open & close tags are just for formatting this comment.
     * Method output should not include pre tags.
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first tag child of the {@code XMLTree} matching the
     *  given tag or -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        for (int i = 0; i < xml.numberOfChildren(); i++) {
            if (xml.child(i).isTag() && xml.child(i).label().equals(tag)) {
                return i;
            }
        }
        return -1;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item")
                : "" + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        out.print("<tr>");

        // Publication Date
        int dateIndex = getChildElement(item, "pubDate");
        String date = "No date available";
        if (dateIndex != -1 && item.child(dateIndex).numberOfChildren() > 0) {
            date = item.child(dateIndex).child(0).label();
        }
        out.print("<td>" + date + "</td>");

        // Source
        int sourceIndex = getChildElement(item, "source");
        if (sourceIndex != -1 && item.child(sourceIndex).numberOfChildren() > 0) {
            String sourceText = item.child(sourceIndex).child(0).label();
            String sourceUrl = item.child(sourceIndex).attributeValue("url");
            out.print("<td><a href=\"" + sourceUrl + "\">" + sourceText + "</a></td>");
        } else {
            out.print("<td>No source available</td>");
        }

        // Title / Description
        int titleIndex = getChildElement(item, "title");
        int descIndex = getChildElement(item, "description");
        String title = "No title available";
        if (titleIndex != -1 && item.child(titleIndex).numberOfChildren() > 0) {
            title = item.child(titleIndex).child(0).label();
        } else if (descIndex != -1 && item.child(descIndex).numberOfChildren() > 0) {
            title = item.child(descIndex).child(0).label();
        }

        int linkIndex = getChildElement(item, "link");
        String link = "";
        if (linkIndex != -1 && item.child(linkIndex).numberOfChildren() > 0) {
            link = item.child(linkIndex).child(0).label();
        }

        if (!link.equals("")) {
            out.print("<td><a href=\"" + link + "\">" + title + "</a></td>");
        } else {
            out.print("<td>" + title + "</td>");
        }

        out.println("</tr>");
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        out.print("Enter the URL of an RSS 2.0 feed: ");
        String url = in.nextLine();

        out.print("Enter the name of the output HTML file: ");
        String fileName = in.nextLine();
        SimpleWriter fileOut = new SimpleWriter1L(fileName);

        XMLTree rss = new XMLTree1(url);
        if (!rss.label().equals("rss") || !rss.hasAttribute("version")
                || !rss.attributeValue("version").equals("2.0")) {
            out.println("Invalid RSS feed.");
        } else {
            XMLTree channel = rss.child(getChildElement(rss, "channel"));
            outputHeader(channel, fileOut);

            for (int i = 0; i < channel.numberOfChildren(); i++) {
                XMLTree child = channel.child(i);
                if (child.isTag() && child.label().equals("item")) {
                    processItem(child, fileOut);
                }
            }

            outputFooter(fileOut);
        }

        in.close();
        out.close();
        fileOut.close();
    }

}
